DROP TABLE IF EXISTS "BANK_CLIENTS";

DROP TABLE IF EXISTS "ACCOUNT_HOLDERS";

DROP TABLE IF EXISTS "BANK_ACCOUNTS";

DROP TABLE IF EXISTS "BANK_CUSTOMERS";

DROP TABLE IF EXISTS "BANK_WRKEX_SALARY";

DROP TABLE IF EXISTS "CHECKING_ACCOUNTS";

DROP TABLE IF EXISTS "SAVINGS_ACCOUNTS";
